---
- name: copy consul-agent configuration file
  template:
    src: "agent.json.j2"
    dest: "{{ consul_conf_agent_dir }}/agent.json"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644
  notify:
    - restart consul-agent
